// Generated by gencpp from file rtabmap_ros/GetMap.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_GETMAP_H
#define RTABMAP_ROS_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <rtabmap_ros/GetMapRequest.h>
#include <rtabmap_ros/GetMapResponse.h>


namespace rtabmap_ros
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::GetMap > {
  static const char* value()
  {
    return "3e091ec560a4c98743c1ae8c5f13ea55";
  }

  static const char* value(const ::rtabmap_ros::GetMap&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::GetMap > {
  static const char* value()
  {
    return "rtabmap_ros/GetMap";
  }

  static const char* value(const ::rtabmap_ros::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::GetMapRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::GetMap > 
template<>
struct MD5Sum< ::rtabmap_ros::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GetMap >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GetMapRequest> should match 
// service_traits::DataType< ::rtabmap_ros::GetMap > 
template<>
struct DataType< ::rtabmap_ros::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GetMap >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::GetMapResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::GetMap > 
template<>
struct MD5Sum< ::rtabmap_ros::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GetMap >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GetMapResponse> should match 
// service_traits::DataType< ::rtabmap_ros::GetMap > 
template<>
struct DataType< ::rtabmap_ros::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GetMap >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_GETMAP_H
