// Generated by gencpp from file rtabmap_ros/ListLabels.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_LISTLABELS_H
#define RTABMAP_ROS_MESSAGE_LISTLABELS_H

#include <ros/service_traits.h>


#include <rtabmap_ros/ListLabelsRequest.h>
#include <rtabmap_ros/ListLabelsResponse.h>


namespace rtabmap_ros
{

struct ListLabels
{

typedef ListLabelsRequest Request;
typedef ListLabelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListLabels
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::ListLabels > {
  static const char* value()
  {
    return "17b562487ca772bdfa2c078ef00d870f";
  }

  static const char* value(const ::rtabmap_ros::ListLabels&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::ListLabels > {
  static const char* value()
  {
    return "rtabmap_ros/ListLabels";
  }

  static const char* value(const ::rtabmap_ros::ListLabels&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::ListLabelsRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::ListLabels > 
template<>
struct MD5Sum< ::rtabmap_ros::ListLabelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::ListLabels >::value();
  }
  static const char* value(const ::rtabmap_ros::ListLabelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::ListLabelsRequest> should match 
// service_traits::DataType< ::rtabmap_ros::ListLabels > 
template<>
struct DataType< ::rtabmap_ros::ListLabelsRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::ListLabels >::value();
  }
  static const char* value(const ::rtabmap_ros::ListLabelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::ListLabelsResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::ListLabels > 
template<>
struct MD5Sum< ::rtabmap_ros::ListLabelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::ListLabels >::value();
  }
  static const char* value(const ::rtabmap_ros::ListLabelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::ListLabelsResponse> should match 
// service_traits::DataType< ::rtabmap_ros::ListLabels > 
template<>
struct DataType< ::rtabmap_ros::ListLabelsResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::ListLabels >::value();
  }
  static const char* value(const ::rtabmap_ros::ListLabelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_LISTLABELS_H
