// Generated by gencpp from file rtabmap_ros/PublishMap.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_PUBLISHMAP_H
#define RTABMAP_ROS_MESSAGE_PUBLISHMAP_H

#include <ros/service_traits.h>


#include <rtabmap_ros/PublishMapRequest.h>
#include <rtabmap_ros/PublishMapResponse.h>


namespace rtabmap_ros
{

struct PublishMap
{

typedef PublishMapRequest Request;
typedef PublishMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PublishMap
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::PublishMap > {
  static const char* value()
  {
    return "6213f9f13cced23f4d224b22f59d839c";
  }

  static const char* value(const ::rtabmap_ros::PublishMap&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::PublishMap > {
  static const char* value()
  {
    return "rtabmap_ros/PublishMap";
  }

  static const char* value(const ::rtabmap_ros::PublishMap&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::PublishMapRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::PublishMap > 
template<>
struct MD5Sum< ::rtabmap_ros::PublishMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::PublishMap >::value();
  }
  static const char* value(const ::rtabmap_ros::PublishMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::PublishMapRequest> should match 
// service_traits::DataType< ::rtabmap_ros::PublishMap > 
template<>
struct DataType< ::rtabmap_ros::PublishMapRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::PublishMap >::value();
  }
  static const char* value(const ::rtabmap_ros::PublishMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::PublishMapResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::PublishMap > 
template<>
struct MD5Sum< ::rtabmap_ros::PublishMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::PublishMap >::value();
  }
  static const char* value(const ::rtabmap_ros::PublishMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::PublishMapResponse> should match 
// service_traits::DataType< ::rtabmap_ros::PublishMap > 
template<>
struct DataType< ::rtabmap_ros::PublishMapResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::PublishMap >::value();
  }
  static const char* value(const ::rtabmap_ros::PublishMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_PUBLISHMAP_H
