// Generated by gencpp from file rtabmap_ros/ResetPose.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_RESETPOSE_H
#define RTABMAP_ROS_MESSAGE_RESETPOSE_H

#include <ros/service_traits.h>


#include <rtabmap_ros/ResetPoseRequest.h>
#include <rtabmap_ros/ResetPoseResponse.h>


namespace rtabmap_ros
{

struct ResetPose
{

typedef ResetPoseRequest Request;
typedef ResetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetPose
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::ResetPose > {
  static const char* value()
  {
    return "3d5697f0c9e8859325238b57521f8f4e";
  }

  static const char* value(const ::rtabmap_ros::ResetPose&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::ResetPose > {
  static const char* value()
  {
    return "rtabmap_ros/ResetPose";
  }

  static const char* value(const ::rtabmap_ros::ResetPose&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::ResetPoseRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::ResetPose > 
template<>
struct MD5Sum< ::rtabmap_ros::ResetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::ResetPose >::value();
  }
  static const char* value(const ::rtabmap_ros::ResetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::ResetPoseRequest> should match 
// service_traits::DataType< ::rtabmap_ros::ResetPose > 
template<>
struct DataType< ::rtabmap_ros::ResetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::ResetPose >::value();
  }
  static const char* value(const ::rtabmap_ros::ResetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::ResetPoseResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::ResetPose > 
template<>
struct MD5Sum< ::rtabmap_ros::ResetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::ResetPose >::value();
  }
  static const char* value(const ::rtabmap_ros::ResetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::ResetPoseResponse> should match 
// service_traits::DataType< ::rtabmap_ros::ResetPose > 
template<>
struct DataType< ::rtabmap_ros::ResetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::ResetPose >::value();
  }
  static const char* value(const ::rtabmap_ros::ResetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_RESETPOSE_H
