// Generated by gencpp from file rtabmap_ros/SetGoal.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_SETGOAL_H
#define RTABMAP_ROS_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <rtabmap_ros/SetGoalRequest.h>
#include <rtabmap_ros/SetGoalResponse.h>


namespace rtabmap_ros
{

struct SetGoal
{

typedef SetGoalRequest Request;
typedef SetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoal
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::SetGoal > {
  static const char* value()
  {
    return "26edc868202251c9d77a8a06444641bb";
  }

  static const char* value(const ::rtabmap_ros::SetGoal&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::SetGoal > {
  static const char* value()
  {
    return "rtabmap_ros/SetGoal";
  }

  static const char* value(const ::rtabmap_ros::SetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::SetGoalRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::SetGoal > 
template<>
struct MD5Sum< ::rtabmap_ros::SetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::SetGoal >::value();
  }
  static const char* value(const ::rtabmap_ros::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::SetGoalRequest> should match 
// service_traits::DataType< ::rtabmap_ros::SetGoal > 
template<>
struct DataType< ::rtabmap_ros::SetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::SetGoal >::value();
  }
  static const char* value(const ::rtabmap_ros::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::SetGoalResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::SetGoal > 
template<>
struct MD5Sum< ::rtabmap_ros::SetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::SetGoal >::value();
  }
  static const char* value(const ::rtabmap_ros::SetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::SetGoalResponse> should match 
// service_traits::DataType< ::rtabmap_ros::SetGoal > 
template<>
struct DataType< ::rtabmap_ros::SetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::SetGoal >::value();
  }
  static const char* value(const ::rtabmap_ros::SetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_SETGOAL_H
