// Generated by gencpp from file rtabmap_ros/SetLabel.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_SETLABEL_H
#define RTABMAP_ROS_MESSAGE_SETLABEL_H

#include <ros/service_traits.h>


#include <rtabmap_ros/SetLabelRequest.h>
#include <rtabmap_ros/SetLabelResponse.h>


namespace rtabmap_ros
{

struct SetLabel
{

typedef SetLabelRequest Request;
typedef SetLabelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLabel
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::SetLabel > {
  static const char* value()
  {
    return "baadfb04a43ec26085eb7bebc9a80862";
  }

  static const char* value(const ::rtabmap_ros::SetLabel&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::SetLabel > {
  static const char* value()
  {
    return "rtabmap_ros/SetLabel";
  }

  static const char* value(const ::rtabmap_ros::SetLabel&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::SetLabelRequest> should match 
// service_traits::MD5Sum< ::rtabmap_ros::SetLabel > 
template<>
struct MD5Sum< ::rtabmap_ros::SetLabelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::SetLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::SetLabelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::SetLabelRequest> should match 
// service_traits::DataType< ::rtabmap_ros::SetLabel > 
template<>
struct DataType< ::rtabmap_ros::SetLabelRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::SetLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::SetLabelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::SetLabelResponse> should match 
// service_traits::MD5Sum< ::rtabmap_ros::SetLabel > 
template<>
struct MD5Sum< ::rtabmap_ros::SetLabelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::SetLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::SetLabelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::SetLabelResponse> should match 
// service_traits::DataType< ::rtabmap_ros::SetLabel > 
template<>
struct DataType< ::rtabmap_ros::SetLabelResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::SetLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::SetLabelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_SETLABEL_H
