(cl:in-package rtabmap_ros-msg)
(cl:export '(ID-VAL
          ID
          MAPID-VAL
          MAPID
          WEIGHT-VAL
          WEIGHT
          STAMP-VAL
          STAMP
          LABEL-VAL
          LABEL
          POSE-VAL
          POSE
          GROUNDTRUTHPOSE-VAL
          GROUNDTRUTHPOSE
          IMAGE-VAL
          IMAGE
          DEPTH-VAL
          DEPTH
          FX-VAL
          FX
          FY-VAL
          FY
          CX-VAL
          CX
          CY-VAL
          CY
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          BASELINE-VAL
          BASELINE
          LOCALTRANSFORM-VAL
          LOCALTRANSFORM
          LASERSCAN-VAL
          LASERSCAN
          LASERSCANMAXPTS-VAL
          LASERSCANMAXPTS
          LASERSCANMAXRANGE-VAL
          LASERSCANMAXRANGE
          LASERSCANLOCALTRANSFORM-VAL
          LASERSCANLOCALTRANSFORM
          USERDATA-VAL
          USERDATA
          GRID_GROUND-VAL
          GRID_GROUND
          GRID_OBSTACLES-VAL
          GRID_OBSTACLES
          GRID_CELL_SIZE-VAL
          GRID_CELL_SIZE
          GRID_VIEW_POINT-VAL
          GRID_VIEW_POINT
          WORDIDS-VAL
          WORDIDS
          WORDKPTS-VAL
          WORDKPTS
          WORDPTS-VAL
          WORDPTS
          DESCRIPTORS-VAL
          DESCRIPTORS
))